# Generated by Django 2.1.7 on 2020-03-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailypost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'MYPost',
                'permissions': [('Can_view_my_post', 'view mypost'), ('Can_add_my_post', 'add mypost'), ('Can_change_my_post', 'Can change data in mypost'), ('Can_delete_my_post', 'Can remove data in mypost')],
            },
        ),
    ]
