# Generated by Django 2.1.7 on 2020-03-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypost',
            options={'permissions': [('Can_view_my_post', 'view mypost'), ('Can_add_my_post', 'add mypost'), ('Can_change_my_post', 'Can change data in mypost'), ('Can_delete_my_post', 'Can remove data in mypost')], 'verbose_name_plural': 'dailypost'},
        ),
    ]
