# Generated by Django 2.0.1 on 2020-09-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='storelocation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
