# Generated by Django 2.0.1 on 2020-10-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stock_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
