# Generated by Django 2.0.1 on 2020-10-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numberofitem',
            field=models.PositiveIntegerField(),
        ),
    ]
