# Generated by Django 2.1.7 on 2019-10-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incoming_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('delivery', models.CharField(max_length=30)),
                ('numberofitem', models.IntegerField()),
                ('damagegoods', models.IntegerField()),
                ('deliveryofficer', models.CharField(max_length=30)),
                ('receivingofficer', models.CharField(max_length=30)),
                ('expirinv_orderydate', models.CharField(max_length=30)),
                ('invoiceNo', models.CharField(max_length=30)),
                ('receipt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mydatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MYPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='neworderux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderper', models.CharField(max_length=30)),
                ('dateorder', models.CharField(max_length=30)),
                ('expecteddatedelivery', models.CharField(max_length=30)),
                ('deliveryofficer', models.CharField(max_length=30)),
                ('invoiceNo', models.CharField(max_length=30)),
                ('receipt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='newstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualityofitem', models.CharField(max_length=30)),
                ('numberofitem', models.IntegerField()),
                ('expirydate', models.CharField(max_length=30)),
                ('officer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofitem', models.IntegerField()),
                ('buyer', models.CharField(max_length=30)),
                ('receipt', models.CharField(max_length=30)),
                ('stateofgood', models.CharField(max_length=30)),
            ],
        ),
    ]
