# Generated by Django 2.1.7 on 2019-11-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_eventform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='message',
            field=models.TextField(),
        ),
    ]
