# Generated by Django 2.1.7 on 2019-12-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_customerorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sales',
            new_name='salex',
        ),
    ]
