# Generated by Django 2.1.7 on 2019-12-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20191221_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mydatabase',
            options={'permissions': [('Can_view_mydatabase', 'view mydatabase'), ('Can_add_mydatabase', 'add entry to the mydatabase'), ('Can_change_mydatabase', 'Can change data in mydatabase'), ('Can_delete_mydatabase', 'Can remove data in mydatabase')]},
        ),
    ]
