# Generated by Django 2.1.7 on 2020-02-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200130_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mydatabase',
            options={'verbose_name_plural': 'mydatabase'},
        ),
    ]
