# Generated by Django 2.1.7 on 2020-02-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200222_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypost',
            options={'permissions': [('Can_view_my_post', 'view mypost'), ('Can_add_my_post', 'can add my post'), ('Can_change_my_post', 'Can change data in mypost'), ('Can_delete_my_post', 'Can remove data in mypost')], 'verbose_name_plural': 'MYPost'},
        ),
    ]
