# Generated by Django 2.1.7 on 2020-02-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200222_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='incoming_purchase',
        ),
        migrations.AlterModelOptions(
            name='mypost',
            options={'permissions': [('Can_view_my_post', 'view mypost'), ('Can_add_my_post', 'add mypost'), ('Can_change_my_post', 'Can change data in mypost'), ('Can_delete_my_post', 'Can remove data in mypost')], 'verbose_name_plural': 'MYPost'},
        ),
    ]
