# Generated by Django 2.1.7 on 2020-02-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20200229_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salex',
        ),
    ]
