# Generated by Django 2.1.7 on 2020-03-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_delete_salex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='neworderux',
        ),
    ]
