# Generated by Django 2.1.7 on 2020-03-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_delete_neworderux'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newstock',
        ),
    ]
