# Generated by Django 2.1.7 on 2020-03-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_delete_newstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MYPost',
        ),
    ]
