# Generated by Django 2.1.7 on 2020-03-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_delete_mypost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVENTform',
        ),
    ]
