# Generated by Django 2.1.7 on 2020-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'EVENTform',
                'permissions': [('Can_view_EVENTform', 'viewEVENTform'), ('Can_add_EVENTform', 'add entry to the EVENTform'), ('Can_change_EVENTform', 'Can change data in EVENTform'), ('Can_delete_EVENTform', 'Can remove data in EVENTform')],
            },
        ),
    ]
