# Generated by Django 2.1.7 on 2020-02-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incoming_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('delivery', models.CharField(max_length=30)),
                ('numberofitem', models.IntegerField()),
                ('damagegoods', models.IntegerField()),
                ('deliveryofficer', models.CharField(max_length=30)),
                ('receivingofficer', models.CharField(max_length=30)),
                ('expirinv_orderydate', models.CharField(max_length=30)),
                ('invoiceNo', models.CharField(max_length=30)),
                ('receipt', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'incoming_purchase',
                'permissions': [('Can_view_incoming_purchase', 'view incoming_purchase'), ('Can_add_incoming_purchase', 'add entry to the incoming_purchase'), ('Can_change_incoming_purchase', 'Can change data in incoming_purchase'), ('Can_delete_incoming_purchase', 'Can remove data in incoming_purchase')],
            },
        ),
    ]
