# Generated by Django 2.1.7 on 2020-03-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderper', models.CharField(max_length=30)),
                ('dateorder', models.CharField(max_length=30)),
                ('expecteddatedelivery', models.CharField(max_length=30)),
                ('deliveryofficer', models.CharField(max_length=30)),
                ('invoiceNo', models.CharField(max_length=30)),
                ('receipt', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'order',
                'permissions': [('Can_view_order', 'view order'), ('Can_add_order', 'add entry to the order'), ('Can_change_order', 'Can change data in order'), ('Can_delete_order', 'Can remove data in order')],
            },
        ),
    ]
