# Generated by Django 2.1.7 on 2020-03-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sales',
            new_name='sale',
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': [('Can_view_sale', 'view sale'), ('Can_add_sale', 'add entry to sale'), ('Can_change_sale', 'Can change data in sale'), ('Can_delete_sale', 'Can remove data in sale')], 'verbose_name_plural': 'sale'},
        ),
    ]
