# Generated by Django 2.0.1 on 2020-10-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200301_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sale',
        ),
    ]
