# Generated by Django 2.0.1 on 2020-10-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='item',
        ),
        migrations.DeleteModel(
            name='sale',
        ),
    ]
