# Generated by Django 2.0.1 on 2020-10-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0009_auto_20201015_0815'),
        ('sales', '0007_auto_20201015_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=30)),
                ('available', models.BooleanField(default=True)),
                ('phone', models.PositiveIntegerField()),
                ('orderno', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock.product')),
            ],
            options={
                'verbose_name_plural': 'sale',
                'permissions': [('Can_view_sale', 'view sale'), ('Can_add_sale', 'add entry to sale'), ('Can_change_sale', 'Can change data in sale'), ('Can_delete_sale', 'Can remove data in sale')],
            },
        ),
    ]
