# Generated by Django 2.0.1 on 2020-10-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='orderno',
            new_name='quantity',
        ),
    ]
