# Generated by Django 2.0.1 on 2020-10-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20201015_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='item',
        ),
        migrations.DeleteModel(
            name='sale',
        ),
    ]
