# Generated by Django 2.0.1 on 2020-10-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='stockavailable',
        ),
    ]
