# Generated by Django 2.0.1 on 2020-10-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_mm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mm',
        ),
    ]
