# Generated by Django 2.0.1 on 2020-11-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_sale_stockavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='stockavailable',
        ),
    ]
