# Generated by Django 2.0.1 on 2020-11-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20201015_0815'),
        ('sales', '0016_remove_sale_stockavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stockavailable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numberofitem1', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='stock.product'),
        ),
    ]
