# Generated by Django 2.0.1 on 2020-11-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20201108_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='stockavailable',
        ),
    ]
